app_calculator:
    path: /calculator
    controller: App\Controller\CalculatorController::getForm

app_calculator_result:
    path: /calculator/post
    controller: App\Controller\CalculatorController::postForm